name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Выберите нужную версию Node.js
      - name: Установить зависимости
        run: npm install -g remark-cli remark-preset-lint-consistent
      - name: Выполнить скрипт в одну строку
        run: echo Hello, world!
      - name: Выполнить многострочный скрипт
        run: |
          echo Добавить другие действия для сборки,
          echo тестирования и развертывания проекта.
      - name: Проверить markdown на соответствие стилю
        run: npx remark . --use remark-preset-lint-consistent --frail
